name = "splpak"
author = "Jacob Williams"
maintainer = "Jacob Williams"
copyright = "Copyright (C) 2000 University Corporation for Atmospheric Research"
license = "Apache"
description = "Modernized SPLPAK library for multidimensional least-squares cubic spline fitting"
homepage = "https://github.com/jacobwilliams/splpak"

[build]
auto-executables = false
auto-examples = false
auto-tests = true

[dev-dependencies]
pyplot-fortran = { git = "https://github.com/jacobwilliams/pyplot-fortran", tag = "3.3.0" }

[library]
source-dir = "src"

[install]
library = true